### ISSUE TITLE
No module named 'optim_orders'

### ISSUE THREAD

**Issue by wang-liangzai** [ZubinGou/multi-view-prompting#2]
Hi, I'm having a bit of a problem trying to reproduce your code. The module optim_orders has not been found, it would be very helpful if you could provide instructions on getting the missing files.Thanks again for making your code public.

**Comment by beeevita** [comment]
Thanks for pointing it out. We have fixed it. Try it now~

**Comment by ZubinGou** [comment]
Hi~ We have updated the environment configuration and conducted code testing with the 4090 and A100 GPUs.
Please refer to the readme for step-by-step guidance on reproducing our setup and running the code successfully.
